import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { TableAndColumnDetails, tableData } from 'src/app/Models/table';
import { DynamicTableService } from 'src/app/Service/dynamicTable.service';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import html2pdf from 'html2pdf.js';
import { storageService } from 'src/app/Service/storageService';

@Component({
  selector: 'app-dynamictables',
  templateUrl: './dynamictables.component.html',
  styleUrls: ['./dynamictables.component.css'],
})
export class DynamictablesComponent implements OnInit {

  window: any;
  date: Date;
  intValue: any;
  Stringvalue: any;
  tableData: TableAndColumnDetails[];
  Genders: string[];

  @ViewChild('dataTables') divToPrint: ElementRef;

  constructor(
    public tableService: DynamicTableService,

    public storageService: storageService
  ) {
    this.Genders = ['Select', 'Male', 'Female'];
  }
  ngAfterViewInit() {}

  ngOnInit(): void {
    this.tableService.getAllTableData().subscribe((data) => {
      this.tableData = data;
      console.log(this.tableData);
    });
  }

  toPdf() {
    let variable = { value: this.divToPrint.nativeElement };
    var toPrint = variable.value.innerHTML;

    toPrint =
      '<div style="text-align: center;">Laurel MES Report</div>' + toPrint;

    var newDate = new Date();
    let footer =
      '<div style="text-align: center;">Generated by ' +
      this.storageService.getSessionItem('userName') +
      ' on ' +
      newDate +
      '</div>';
    console.log(toPrint);

    const settings = {
      margin: [5, 10, 2, 10], // Set margins (left, top, right, bottom)
      filename: 'Data Tables.pdf',
      image: { type: 'jpeg', quality: 100 },
      html2canvas: { scale: 2, logging: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'landscape' }, // Adjust orientation here
      footer: { footer },
    };

    html2pdf().from(toPrint).set(settings).save('example.pdf');

    setTimeout(() => {
      this.ngOnInit();
    }, 200);
  }

  editRow(data: tableData) {
    data.editflag = true;
    console.log(data);
  }
  saveRow(data: tableData,slNo: number,tableNo: number) {
    console.log(data,slNo,tableNo);

    }

}
